services:
  frontend:
    container_name: react-frontend
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # server 3000 : container 80
    restart: always
    depends_on:
      - backend

  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # server 8000 : container 8000
    restart: always