services:
  frontend:
    container_name: react-frontend
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # server 3000 : container 80
    restart: always
    depends_on:
      - backend
    # command: 
    #   ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # server 8000 : container 8000
    restart: always
    # command: 
    #   ["npm", "run", "preview"]
  
  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend